"""Walkthrough documents.

The walkthroughs are documentation generated from real tool output, and they
are committed. That combination rots: someone changes an output shape, the
committed markdown keeps describing the old one, and the most visible docs in
the repo become wrong.

`test_committed_walkthroughs_are_current` is the guard. It regenerates and
compares, so a change to any tool output that reaches a walkthrough fails the
suite until `make walkthroughs` is run.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from examples.walkthroughs.build import HERE, WALKTHROUGHS, main, render_all


@pytest.fixture(scope="module")
def rendered(tmp_path_factory: pytest.TempPathFactory) -> dict[str, str]:
    return render_all(tmp_path_factory.mktemp("wt"))


def test_committed_walkthroughs_are_current(rendered: dict[str, str]) -> None:
    """Run `make walkthroughs` if this fails."""
    stale = [
        name
        for name, text in rendered.items()
        if not (HERE / name).exists() or (HERE / name).read_text() != text
    ]
    assert stale == [], f"stale walkthroughs: {stale}; run `make walkthroughs`"


def test_check_mode_agrees(tmp_path: Path) -> None:
    """The `--check` entry point CI would use returns success on a clean tree."""
    assert main(["--check"]) == 0


def test_every_declared_walkthrough_was_written(rendered: dict[str, str]) -> None:
    assert set(rendered) == set(WALKTHROUGHS)
    for name in WALKTHROUGHS:
        assert (HERE / name).exists(), name


def test_generation_is_deterministic(tmp_path_factory: pytest.TempPathFactory) -> None:
    """Two runs in different working directories must agree, or the committed
    files would churn on every rebuild."""
    a = render_all(tmp_path_factory.mktemp("a"))
    b = render_all(tmp_path_factory.mktemp("b"))
    assert a == b


@pytest.mark.parametrize("name", list(WALKTHROUGHS))
def test_walkthrough_carries_the_do_not_edit_banner(name: str, rendered: dict[str, str]) -> None:
    assert rendered[name].startswith("<!-- Generated by")


@pytest.mark.parametrize("name", list(WALKTHROUGHS))
def test_no_unrendered_placeholders(name: str, rendered: dict[str, str]) -> None:
    """No leftover stubs, and no f-string that failed to interpolate.

    Braces on their own are expected — these documents embed JSON. What would
    signal a bug is a brace wrapping a bare identifier, which is what an
    unrendered `{variable}` looks like.
    """
    text = rendered[name]
    for bad in ("TODO", "TBD", "FIXME", "XXX"):
        assert bad not in text, f"{name} contains {bad!r}"
    unrendered = re.findall(r"\{[a-z_][a-z_0-9.\[\]]*\}", text)
    assert unrendered == [], f"{name} has unrendered placeholders: {unrendered}"


def _json_blocks(text: str) -> list[str]:
    return re.findall(r"```json\n(.*?)```", text, flags=re.DOTALL)


@pytest.mark.parametrize("name", list(WALKTHROUGHS))
def test_json_blocks_are_valid_json(name: str, rendered: dict[str, str]) -> None:
    """Every fenced block claims to be tool output. If it will not parse, the
    document is showing something the caller would never receive."""
    blocks = _json_blocks(rendered[name])
    assert blocks, f"{name} shows no tool output"
    for block in blocks:
        json.loads(block)


@pytest.mark.parametrize("name", list(WALKTHROUGHS))
def test_no_python_repr_leaked_into_the_json(name: str, rendered: dict[str, str]) -> None:
    """Scoped to the fences: `None`, `nan`, or single-quoted keys inside a JSON
    block mean a Python object was formatted rather than serialised. Prose is
    exempt, since English legitimately contains apostrophes."""
    for block in _json_blocks(rendered[name]):
        for bad in ("None", "nan", "Infinity", "'"):
            assert bad not in block, f"{name} JSON contains {bad!r} — repr() output"


def test_qc_walkthrough_names_every_planted_defect(rendered: dict[str, str]) -> None:
    """The document's whole argument is that the tools found what was planted,
    so each defect kind must actually appear in it."""
    text = rendered["01-qc-a-well-log.md"]
    for kind in ("null_gap", "washout", "spike"):
        assert kind in text, kind
    # The exact intervals, so the prose cannot describe a different well.
    assert "6600" in text and "6640" in text, "null gap interval missing"
    assert "7210" in text and "7255" in text, "washout interval missing"


def test_compare_walkthrough_names_the_three_findings(rendered: dict[str, str]) -> None:
    text = rendered["02-compare-two-wells.md"]
    assert "DT" in text, "the curve unique to A"
    assert "NPHI" in text, "the mismatched curve"
    assert "5200" in text and "8600" in text, "depth overlap missing"


def test_units_walkthrough_lists_every_quantity(rendered: dict[str, str]) -> None:
    from petromcp.utils.units import supported_units

    text = rendered["03-unit-conversion.md"]
    for quantity in {p.quantity for p in supported_units().pairs}:
        assert quantity in text, quantity
