"""Generate the walkthrough documents from real tool output.

Every number, curve name, and depth in `examples/walkthroughs/*.md` is
produced by calling the actual petromcp tools against a freshly generated
synthetic well. Nothing is transcribed by hand.

That matters because a walkthrough is a claim about what the software does.
Hand-written examples drift silently the moment a signature or an output shape
changes, and a stale example in the README is worse than none — it is a
documented lie. `tests/test_walkthroughs.py` regenerates these files and fails
if the committed copies are out of date, so the docs cannot rot.

The generated files ARE committed, unlike the synthetic LAS files, because
they are documentation rather than data. Rebuild with `make walkthroughs`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from examples.sample_data.generate import generate, truth_path_for
from examples.sample_data.truth import WellTruth
from examples.sample_data.wells import WELLS
from petromcp.models.shared import DepthRange
from petromcp.tools.compare import compare_well_logs
from petromcp.tools.las import read_las_curve, read_las_file, summarize_las_curves
from petromcp.utils.units import supported_units

HERE = Path(__file__).resolve().parent

BANNER = (
    "<!-- Generated by examples/walkthroughs/build.py. Do not edit by hand:\n"
    "     every value below is real tool output, and tests/test_walkthroughs.py\n"
    "     fails if this file drifts from what the tools currently return. -->"
)


def _fence(payload: Any, lang: str = "json") -> str:
    if hasattr(payload, "model_dump"):
        payload = payload.model_dump()
    text = json.dumps(payload, indent=2, default=str)
    return f"```{lang}\n{text}\n```"


def _trim_curve(data: Any, keep: int = 4) -> dict:
    """Curve reads are long. Show the head and record what was elided."""
    d = data.model_dump()
    total = len(d["depths"])
    d["depths"] = d["depths"][:keep]
    d["values"] = [round(v, 4) if isinstance(v, float) else v for v in d["values"][:keep]]
    d["_elided"] = f"{total - keep} further samples omitted from this document"
    return d


def _defect_table(truth: WellTruth) -> str:
    rows = ["| Defect | Curve | Interval | Detail |", "|---|---|---|---|"]
    for d in truth.defects:
        interval = (
            f"{d.top:.1f}-{d.base:.1f} ft"
            if d.top is not None and d.base is not None and d.top != d.base
            else (f"{d.top:.1f} ft" if d.top is not None else "-")
        )
        detail = ""
        if d.magnitude is not None:
            detail = f"value {d.magnitude:g}"
        elif d.declared_unit is not None:
            detail = f"header declares `{d.declared_unit}`"
        rows.append(f"| `{d.kind}` | {d.curve or '-'} | {interval} | {detail} |")
    return "\n".join(rows)


def build_qc_walkthrough(work: Path) -> str:
    spec = WELLS["SYNTH-01"]
    las, _ = generate(spec, work / "SYNTH-01.las")
    truth = WellTruth.model_validate_json(truth_path_for(las).read_text())
    roots = [work]

    header = read_las_file(str(las), roots)
    summary = summarize_las_curves(str(las), roots)
    washout = next(d for d in truth.defects_for("washout"))
    assert washout.top is not None and washout.base is not None
    cali = read_las_curve(
        str(las),
        "CALI",
        depth_range=DepthRange(start=washout.top, stop=washout.base),
        allowed_paths=roots,
    )

    gap = next(d for d in truth.defects_for("null_gap"))
    spike = next(d for d in truth.defects_for("spike"))
    gr = next(c for c in summary.curves if c.name == "GR")
    rhob = next(c for c in summary.curves if c.name == "RHOB")
    cali_stats = next(c for c in summary.curves if c.name == "CALI")

    return f"""{BANNER}

# Walkthrough: QC a well log

What a standard quality-control pass looks like when Claude drives petromcp.
The well is synthetic and its problems were planted deliberately, so you can
check the tool found what was actually there rather than take the output on
faith.

## The planted problems

`make generate` writes a ground-truth manifest beside every synthetic LAS
recording exactly what it injected:

{_defect_table(truth)}

A petrophysicist should find all of these. So should the tools.

## Step 1 — identify the well

> What's wrong with this well log? `synthetic_well_01.las`

Claude starts with the cheapest call, which returns header metadata and no
curve data at all:

{_fence(header)}

{header.total_points} depth samples over
{header.depth_start:.0f}-{header.depth_stop:.0f} {header.depth_units}, with
the expected open-hole triple combo present. Note `gap_summary` already
reports {header.gap_summary.total_gaps} depth gap(s) before any curve has
been read.

## Step 2 — per-curve statistics

{_fence(summary)}

Three things stand out, and each one is a planted defect:

- **RHOB has a {rhob.gap_percentage}% gap.** That is the null interval at
  {gap.top:.0f}-{gap.base:.0f} ft where the density tool dropped out. Every
  other curve reads {gr.gap_percentage}%.
- **GR maxes at {gr.max:.1f} GAPI.** Gamma ray in shale runs 100-140; a
  single sample at {spike.magnitude:g} is not a rock, it is the spike planted
  at {spike.top:.0f} ft.
- **CALI maxes at {cali_stats.max:.2f} in against an 8.5 in bit.** The hole is
  enlarged somewhere. Statistics alone cannot say where.

## Step 3 — scope the caliper anomaly

The summary says *that* the hole is washed out, not *where*. This is the one
case worth reading actual samples, so the depth interval is passed explicitly
— which disables the default 500-sample downsample and returns every point:

{_fence(_trim_curve(cali))}

`downsampled: {str(cali.downsampled).lower()}` and
`sample_count: {cali.sample_count}` confirm nothing was thinned. The caliper
reads above bit size across {washout.top:.0f}-{washout.base:.0f} ft, which is
the washout the manifest recorded. Density in the same interval reads light,
because the tool has lost contact with the formation — the two curves moving
together is what distinguishes a washout from a bad density calibration.

## What this demonstrates

Every finding above corresponds to a row in the manifest table, and the eval
in `evals/scenarios/01_well_log_qc.yaml` asserts exactly that correspondence
on every run. The walkthrough is not a story about the tools working; it is
the same check CI performs, written out.

Also worth noting what did *not* happen: at no point were {header.total_points}
depth samples sent to the model. Two summary calls and one scoped read of
{cali.sample_count} samples were enough to locate all three problems.
"""


def build_compare_walkthrough(work: Path) -> str:
    las_a, _ = generate(WELLS["SYNTH-01"], work / "SYNTH-01.las")
    las_b, _ = generate(WELLS["SYNTH-02"], work / "SYNTH-02.las")
    truth_b = WellTruth.model_validate_json(truth_path_for(las_b).read_text())
    report = compare_well_logs(str(las_a), str(las_b), [work])
    mismatch = next(iter(truth_b.defects_for("unit_mismatch")), None)
    overlap = report.depth_overlap
    assert overlap is not None

    return f"""{BANNER}

# Walkthrough: compare two wells

Comparing an offset well against a reference well. As with the QC
walkthrough, the differences were planted, so the output can be checked
rather than trusted.

## The planted differences

SYNTH-02 differs from SYNTH-01 in three deliberate ways: a shorter depth
range, no sonic curve, and a neutron curve whose header lies about its units.

{_defect_table(truth_b)}

The unit mismatch is the interesting one. The NPHI *values* are correct
fractional porosity; only the declared unit is wrong. Nothing inside
SYNTH-02 alone can reveal that — it is invisible until the file is compared
against one that declares the same curve honestly.

## The comparison

> Compare these two wells: `synthetic_well_01.las` and `synthetic_well_02.las`

{_fence(report)}

## Reading the flags

- **Depth overlap {overlap.start:.0f}-{overlap.stop:.0f} ft.** The wells share
  that interval and nothing outside it. Any curve-on-curve comparison beyond
  those depths would be comparing one well against nothing.
- **`{", ".join(report.unique_to_a) or "none"}` present in A only.** No sonic
  was run on the offset well, so any workflow expecting DT will need a
  different input for SYNTH-02.
- **Unit mismatch on {mismatch.curve if mismatch else "NPHI"}.** A reads
  `v/v`, B declares `{mismatch.declared_unit if mismatch else "%"}`. Anyone
  cross-plotting these without noticing would be off by a factor of 100 — the
  kind of error that survives review because both numbers look plausible on
  their own.

{len(report.common_curves)} curves are common to both wells
(`{", ".join(report.common_curves)}`), and the unit check ran on all of them.

## Why strict matching

Curve mnemonics and units are compared case-sensitively and without
normalisation. `V/V` is not `v/v`. That produces occasional false positives on
real data, and that is the intended trade: a false flag costs a moment's
reading, while a missed unit mismatch propagates silently into whatever is
computed next.
"""


def build_units_walkthrough(work: Path) -> str:
    units = supported_units()
    by_quantity: dict[str, list[str]] = {}
    for pair in units.pairs:
        by_quantity.setdefault(pair.quantity, []).append(
            f"{pair.from_unit} -> {pair.to_unit}"
        )
    rows = "\n".join(
        f"| {quantity} | {', '.join(sorted(pairs))} |"
        for quantity, pairs in sorted(by_quantity.items())
    )

    return f"""{BANNER}

# Walkthrough: unit conversion

A small tool, included because getting it wrong is expensive and because
discoverability matters more than it looks.

## Ask what is supported before converting

> What units can you convert?

{_fence(units)}

{len(units.pairs)} directed pairs across {len(by_quantity)} quantities:

| Quantity | Pairs |
|---|---|
{rows}

Both directions of every pair are listed, and the table is derived from the
same lookup the converter uses — so it cannot advertise a conversion that
would then be rejected.

## Then convert

> Convert 1500 psi to kPa.

Matching is strict and case-sensitive: `Ft` is not `ft`, and `PSI` is not
`psi`. An unsupported pair raises rather than guessing, and the error names
the pairs that do work.

This is why the discovery tool exists. Without it the only way to learn the
supported spellings is to call the converter wrong and read the error, which
costs a round trip and looks like a failure to the person watching.
"""


WALKTHROUGHS = {
    "01-qc-a-well-log.md": build_qc_walkthrough,
    "02-compare-two-wells.md": build_compare_walkthrough,
    "03-unit-conversion.md": build_units_walkthrough,
}


def render_all(work: Path) -> dict[str, str]:
    """Render every walkthrough. Pure apart from generating wells into `work`."""
    return {name: builder(work) for name, builder in WALKTHROUGHS.items()}


def main(argv: list[str] | None = None) -> int:
    import argparse
    import tempfile

    p = argparse.ArgumentParser(description="build the walkthrough documents")
    p.add_argument("--check", action="store_true", help="fail if committed files are stale")
    args = p.parse_args(argv)

    with tempfile.TemporaryDirectory() as tmp:
        rendered = render_all(Path(tmp))

    stale: list[str] = []
    for name, text in rendered.items():
        target = HERE / name
        if args.check:
            if not target.exists() or target.read_text() != text:
                stale.append(name)
        else:
            target.write_text(text)
            print(f"wrote {target.relative_to(HERE.parents[1])}")

    if args.check:
        if stale:
            print("stale walkthroughs: " + ", ".join(stale))
            print("run `make walkthroughs` to regenerate")
            return 1
        print(f"{len(rendered)} walkthrough(s) up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
