"""Generate the walkthrough documents from real tool output.

Every number, curve name, and depth in `examples/walkthroughs/*.md` is
produced by calling the actual petromcp tools against a freshly generated
synthetic well. Nothing is transcribed by hand.

That matters because a walkthrough is a claim about what the software does.
Hand-written examples drift silently the moment a signature or an output shape
changes, and a stale example in the README is worse than none — it is a
documented lie. `tests/test_walkthroughs.py` regenerates these files and fails
if the committed copies are out of date, so the docs cannot rot.

The generated files ARE committed, unlike the synthetic LAS files, because
they are documentation rather than data. Rebuild with `make walkthroughs`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from examples.sample_data.dlis_generate import generate as generate_dlis
from examples.sample_data.dlis_generate import truth_path_for as dlis_truth_path_for
from examples.sample_data.dlis_wells import DLIS_WELLS
from examples.sample_data.generate import generate, truth_path_for
from examples.sample_data.truth import WellTruth
from examples.sample_data.wells import WELLS
from petromcp.models.shared import DepthRange
from petromcp.tools.compare import compare_well_logs
from petromcp.tools.dlis import (
    AmbiguousChannelError,
    list_dlis_channels,
    read_dlis_channel,
    read_dlis_file,
)
from petromcp.tools.las import read_las_curve, read_las_file, summarize_las_curves
from petromcp.utils.units import supported_units

HERE = Path(__file__).resolve().parent

BANNER = (
    "<!-- Generated by examples/walkthroughs/build.py. Do not edit by hand:\n"
    "     every value below is real tool output, and tests/test_walkthroughs.py\n"
    "     fails if this file drifts from what the tools currently return. -->"
)


def _fence(payload: Any, lang: str = "json") -> str:
    if hasattr(payload, "model_dump"):
        payload = payload.model_dump()
    text = json.dumps(payload, indent=2, default=str)
    return f"```{lang}\n{text}\n```"


def _trim_curve(data: Any, keep: int = 4) -> dict:
    """Curve reads are long. Show the head and record what was elided.

    Handles both curve models: the LAS one names its axis `depths`, the DLIS one
    names it `index` because a DLIS frame may be indexed on time rather than
    depth. Detecting the key beats maintaining two near-identical helpers.
    """
    d = data.model_dump()
    axis = "depths" if "depths" in d else "index"
    total = len(d[axis])
    d[axis] = [round(v, 4) if isinstance(v, float) else v for v in d[axis][:keep]]
    d["values"] = [round(v, 4) if isinstance(v, float) else v for v in d["values"][:keep]]
    d["_elided"] = f"{total - keep} further samples omitted from this document"
    return d


def _defect_table(truth: WellTruth) -> str:
    rows = ["| Defect | Curve | Interval | Detail |", "|---|---|---|---|"]
    for d in truth.defects:
        interval = (
            f"{d.top:.1f}-{d.base:.1f} ft"
            if d.top is not None and d.base is not None and d.top != d.base
            else (f"{d.top:.1f} ft" if d.top is not None else "-")
        )
        detail = ""
        if d.magnitude is not None:
            detail = f"value {d.magnitude:g}"
        elif d.declared_unit is not None:
            detail = f"header declares `{d.declared_unit}`"
        rows.append(f"| `{d.kind}` | {d.curve or '-'} | {interval} | {detail} |")
    return "\n".join(rows)


def build_qc_walkthrough(work: Path) -> str:
    spec = WELLS["SYNTH-01"]
    las, _ = generate(spec, work / "SYNTH-01.las")
    truth = WellTruth.model_validate_json(truth_path_for(las).read_text())
    roots = [work]

    header = read_las_file(str(las), roots)
    summary = summarize_las_curves(str(las), roots)
    washout = next(d for d in truth.defects_for("washout"))
    assert washout.top is not None and washout.base is not None
    cali = read_las_curve(
        str(las),
        "CALI",
        depth_range=DepthRange(start=washout.top, stop=washout.base),
        allowed_paths=roots,
    )

    gap = next(d for d in truth.defects_for("null_gap"))
    spike = next(d for d in truth.defects_for("spike"))
    gr = next(c for c in summary.curves if c.name == "GR")
    rhob = next(c for c in summary.curves if c.name == "RHOB")
    cali_stats = next(c for c in summary.curves if c.name == "CALI")

    return f"""{BANNER}

# Walkthrough: QC a well log

What a standard quality-control pass looks like when Claude drives petromcp.
The well is synthetic and its problems were planted deliberately, so you can
check the tool found what was actually there rather than take the output on
faith.

## The planted problems

`make generate` writes a ground-truth manifest beside every synthetic LAS
recording exactly what it injected:

{_defect_table(truth)}

A petrophysicist should find all of these. So should the tools.

## Step 1 — identify the well

> What's wrong with this well log? `synthetic_well_01.las`

Claude starts with the cheapest call, which returns header metadata and no
curve data at all:

{_fence(header)}

{header.total_points} depth samples over
{header.depth_start:.0f}-{header.depth_stop:.0f} {header.depth_units}, with
the expected open-hole triple combo present. Note `gap_summary` already
reports {header.gap_summary.total_gaps} depth gap(s) before any curve has
been read.

## Step 2 — per-curve statistics

{_fence(summary)}

Three things stand out, and each one is a planted defect:

- **RHOB has a {rhob.gap_percentage}% gap.** That is the null interval at
  {gap.top:.0f}-{gap.base:.0f} ft where the density tool dropped out. Every
  other curve reads {gr.gap_percentage}%.
- **GR maxes at {gr.max:.1f} GAPI.** Gamma ray in shale runs 100-140; a
  single sample at {spike.magnitude:g} is not a rock, it is the spike planted
  at {spike.top:.0f} ft.
- **CALI maxes at {cali_stats.max:.2f} in against an 8.5 in bit.** The hole is
  enlarged somewhere. Statistics alone cannot say where.

## Step 3 — scope the caliper anomaly

The summary says *that* the hole is washed out, not *where*. This is the one
case worth reading actual samples, so the depth interval is passed explicitly
— which disables the default 500-sample downsample and returns every point:

{_fence(_trim_curve(cali))}

`downsampled: {str(cali.downsampled).lower()}` and
`sample_count: {cali.sample_count}` confirm nothing was thinned. The caliper
reads above bit size across {washout.top:.0f}-{washout.base:.0f} ft, which is
the washout the manifest recorded. Density in the same interval reads light,
because the tool has lost contact with the formation — the two curves moving
together is what distinguishes a washout from a bad density calibration.

## What this demonstrates

Every finding above corresponds to a row in the manifest table, and the eval
in `evals/scenarios/01_well_log_qc.yaml` asserts exactly that correspondence
on every run. The walkthrough is not a story about the tools working; it is
the same check CI performs, written out.

Also worth noting what did *not* happen: at no point were {header.total_points}
depth samples sent to the model. Two summary calls and one scoped read of
{cali.sample_count} samples were enough to locate all three problems.
"""


def build_compare_walkthrough(work: Path) -> str:
    las_a, _ = generate(WELLS["SYNTH-01"], work / "SYNTH-01.las")
    las_b, _ = generate(WELLS["SYNTH-02"], work / "SYNTH-02.las")
    truth_b = WellTruth.model_validate_json(truth_path_for(las_b).read_text())
    report = compare_well_logs(str(las_a), str(las_b), [work])
    mismatch = next(iter(truth_b.defects_for("unit_mismatch")), None)
    overlap = report.depth_overlap
    assert overlap is not None

    return f"""{BANNER}

# Walkthrough: compare two wells

Comparing an offset well against a reference well. As with the QC
walkthrough, the differences were planted, so the output can be checked
rather than trusted.

## The planted differences

SYNTH-02 differs from SYNTH-01 in three deliberate ways: a shorter depth
range, no sonic curve, and a neutron curve whose header lies about its units.

{_defect_table(truth_b)}

The unit mismatch is the interesting one. The NPHI *values* are correct
fractional porosity; only the declared unit is wrong. Nothing inside
SYNTH-02 alone can reveal that — it is invisible until the file is compared
against one that declares the same curve honestly.

## The comparison

> Compare these two wells: `synthetic_well_01.las` and `synthetic_well_02.las`

{_fence(report)}

## Reading the flags

- **Depth overlap {overlap.start:.0f}-{overlap.stop:.0f} ft.** The wells share
  that interval and nothing outside it. Any curve-on-curve comparison beyond
  those depths would be comparing one well against nothing.
- **`{", ".join(report.unique_to_a) or "none"}` present in A only.** No sonic
  was run on the offset well, so any workflow expecting DT will need a
  different input for SYNTH-02.
- **Unit mismatch on {mismatch.curve if mismatch else "NPHI"}.** A reads
  `v/v`, B declares `{mismatch.declared_unit if mismatch else "%"}`. Anyone
  cross-plotting these without noticing would be off by a factor of 100 — the
  kind of error that survives review because both numbers look plausible on
  their own.

{len(report.common_curves)} curves are common to both wells
(`{", ".join(report.common_curves)}`), and the unit check ran on all of them.

## Why strict matching

Curve mnemonics and units are compared case-sensitively and without
normalisation. `V/V` is not `v/v`. That produces occasional false positives on
real data, and that is the intended trade: a false flag costs a moment's
reading, while a missed unit mismatch propagates silently into whatever is
computed next.
"""


def build_units_walkthrough(work: Path) -> str:
    units = supported_units()
    by_quantity: dict[str, list[str]] = {}
    for pair in units.pairs:
        by_quantity.setdefault(pair.quantity, []).append(
            f"{pair.from_unit} -> {pair.to_unit}"
        )
    rows = "\n".join(
        f"| {quantity} | {', '.join(sorted(pairs))} |"
        for quantity, pairs in sorted(by_quantity.items())
    )

    return f"""{BANNER}

# Walkthrough: unit conversion

A small tool, included because getting it wrong is expensive and because
discoverability matters more than it looks.

## Ask what is supported before converting

> What units can you convert?

{_fence(units)}

{len(units.pairs)} directed pairs across {len(by_quantity)} quantities:

| Quantity | Pairs |
|---|---|
{rows}

Both directions of every pair are listed, and the table is derived from the
same lookup the converter uses — so it cannot advertise a conversion that
would then be rejected.

## Then convert

> Convert 1500 psi to kPa.

Matching is strict and case-sensitive: `Ft` is not `ft`, and `PSI` is not
`psi`. An unsupported pair raises rather than guessing, and the error names
the pairs that do work.

This is why the discovery tool exists. Without it the only way to learn the
supported spellings is to call the converter wrong and read the error, which
costs a round trip and looks like a failure to the person watching.
"""


def build_dlis_walkthrough(work: Path) -> str:
    spec = DLIS_WELLS["DSYNTH-01"]
    path, _ = generate_dlis(spec, work / "DSYNTH-01.dlis")
    truth = WellTruth.model_validate_json(dlis_truth_path_for(path).read_text())
    roots = [work]

    summary = read_dlis_file(str(path), roots)
    listing = list_dlis_channels(str(path), roots, frame="SONIC")
    washout = next(iter(truth.defects_for("washout")))
    assert washout.top is not None and washout.base is not None
    cali = read_dlis_channel(
        str(path), "CALI",
        depth_start=washout.top, depth_stop=washout.base, allowed_paths=roots,
    )

    # The ambiguity path, shown with the real error rather than described.
    multi_path, _ = generate_dlis(DLIS_WELLS["DSYNTH-02"], work / "DSYNTH-02.dlis")
    frame_names = [f.name for lf in summary.logical_files for f in lf.frames]

    return f"""{BANNER}

# Walkthrough: read a DLIS file

DLIS is where the shape of the data stops resembling LAS. One physical file
holds several *logical files* — separate logging runs — each holding several
*frames*, each holding *channels*. A channel name is unique only within a
frame.

That structure is why the DLIS tools take a different shape from the LAS ones,
and why one of them refuses to answer a question it cannot answer unambiguously.

## Step 1 — what is in the file

> What's in this DLIS? `synthetic_dlis_01.dlis`

The cheap structural call comes first. A real DLIS can carry hundreds of
channels, so reading them just to describe the file would cost more than the
answer is worth:

{_fence(summary)}

{summary.total_frames} frames ({", ".join(frame_names)}) carrying
{summary.total_channels} channels. Each frame has its own index channel and its
own depth range, because frames are recorded independently — a sonic pass and a
density pass are not sampled at the same rate, and DLIS does not pretend
otherwise.

Note what is absent: no channel values. That is the point of this call.

## Step 2 — find the channels you want

> What's on the sonic frame?

{_fence(listing)}

Every row carries its frame and logical file. Without those a listing looks
addressable but is not, because the same channel name can appear on more than
one frame.

## Step 3 — read one channel over an interval

The generator planted a washout at {washout.top:.0f}-{washout.base:.0f} ft.
Passing the interval explicitly disables the default downsample:

{_fence(_trim_curve(cali))}

`downsampled: {str(cali.downsampled).lower()}`, {cali.sample_count} samples,
caliper above the 8.5 in bit size across the whole interval — the washout, from
a file whose manifest says it is there.

## When a channel name is ambiguous

`synthetic_dlis_02.dlis` is a two-run file. Ask for a channel that exists in
more than one place and petromcp does **not** choose:

```text
{_ambiguity_message(multi_path, work)}
```

That is deliberate. The values differ between frames, so picking one silently
would return a plausible wrong answer — the worst possible outcome for a tool a
model is driving without a human reading every step. Naming the frame resolves
it.

## What this demonstrates

The three tools form a funnel: structure, then channels, then values. Each step
narrows what the next one has to read, which is what keeps a format that can
hold hundreds of channels inside a context window.
"""


def _ambiguity_message(path: Path, work: Path, channel: str = "GR") -> str:
    """The real refusal text, captured by triggering it.

    Raises rather than returning placeholder text if the file turns out to have
    no ambiguous channel. An earlier version returned "(no ambiguity in this
    file)" and cheerfully published a walkthrough that described a behaviour it
    had not demonstrated — the documented lie this whole build step exists to
    prevent.
    """
    try:
        read_dlis_channel(str(path), channel, allowed_paths=[work])
    except AmbiguousChannelError as exc:
        return str(exc)
    raise AssertionError(
        f"{path.name} has no ambiguous channel {channel!r}, so the walkthrough "
        "cannot show the refusal it describes. Fix the fixture, not this text."
    )


WALKTHROUGHS = {
    "01-qc-a-well-log.md": build_qc_walkthrough,
    "02-compare-two-wells.md": build_compare_walkthrough,
    "03-unit-conversion.md": build_units_walkthrough,
    "04-read-a-dlis-file.md": build_dlis_walkthrough,
}


def render_all(work: Path) -> dict[str, str]:
    """Render every walkthrough. Pure apart from generating wells into `work`."""
    return {name: builder(work) for name, builder in WALKTHROUGHS.items()}


def main(argv: list[str] | None = None) -> int:
    import argparse
    import tempfile

    p = argparse.ArgumentParser(description="build the walkthrough documents")
    p.add_argument("--check", action="store_true", help="fail if committed files are stale")
    args = p.parse_args(argv)

    with tempfile.TemporaryDirectory() as tmp:
        rendered = render_all(Path(tmp))

    stale: list[str] = []
    for name, text in rendered.items():
        target = HERE / name
        if args.check:
            if not target.exists() or target.read_text() != text:
                stale.append(name)
        else:
            target.write_text(text)
            print(f"wrote {target.relative_to(HERE.parents[1])}")

    if args.check:
        if stale:
            print("stale walkthroughs: " + ", ".join(stale))
            print("run `make walkthroughs` to regenerate")
            return 1
        print(f"{len(rendered)} walkthrough(s) up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
